// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaglikProje.Models;

namespace SaglikProje.Migrations
{
    [DbContext(typeof(SaglikProjesiContext))]
    [Migration("20221109171453_Belirti_Table")]
    partial class Belirti_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SaglikProje.Models.Belirti", b =>
                {
                    b.Property<int>("BelirtiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Belirtiler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BelirtiId");

                    b.ToTable("Belirtis");
                });
#pragma warning restore 612, 618
        }
    }
}
